export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAIL = 'GET_ARTICLE_LIST_FAIL';

export const GET_COMMENTS_LIST_REQUEST = 'GET_COMMENTS_LIST_REQUEST';
export const GET_COMMENTS_LIST_SUCCESS = 'GET_COMMENTS_LIST_SUCCESS';
export const GET_COMMENTS_LIST_FAIL = 'GET_COMMENTS_LIST_FAIL';

export const CLICK_LIKE = 'CLICK_LIKE';